### PR TITLE
Update Sphinx version for main branch (3.11)

### PR DESCRIPTION
**Pull request by m-aciek**
It has been updated in Docs/requirements.txt of CPython at 31 of October 2021.
https://github.com/python/cpython/commit/14a4fce457033412278ca9a056787db424310dc3

### CODE REVIEW

**Comment by JulienPalard** [comment]
If it close https://github.com/python/docsbuild-scripts/issues/122 I'll sleep well thanks to this PR, thank you!

**Comment by m-aciek** [comment]
I didn't check if it fixes it. But still there's a chance. :fingerscrossed:

**Comment by JulienPalard** [comment]
It works \o/

I don't know if you went here after spotting https://bugs.python.org/issue44006 or #122 or something else, but the PR lands at the right moment, made my day :))

**Comment by m-aciek** [comment]
I've seen the issue and noticed the difference in the Sphinx versions between here and CPython repository. Cheers :)

**Pull request merged**
