### PR TITLE
Migrate sentry from 1.x to 2.x

### PR DESCRIPTION
**Pull request by egeakman**
This resolves the deprecation warning reported in #181.

### CODE REVIEW

**Review by AA-Turner — APPROVED** [review]
xref: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#scope-configuring

A

**Comment by AA-Turner** [comment]
@egeakman -- perhaps add a constraint to https://github.com/python/docsbuild-scripts/blob/main/requirements.txt#L3?

**Comment by egeakman** [comment]
> @egeakman -- perhaps add a constraint to https://github.com/python/docsbuild-scripts/blob/main/requirements.txt#L3?

Will do tomorrow, thanks :heart:

**Comment by egeakman** [comment]
Should be good to go

**Pull request merged**
