### PR TITLE
Enable the Polish translation in the language switcher

### PR DESCRIPTION
**Pull request by StanFromIreland**
I believe this is all that is necessary. If there is much more to be done I can close my PR and let someone who knows the config better do this.

### CODE REVIEW

**Comment by hugovk** [comment]
Here's what's needed before adding to the switcher: https://peps.python.org/pep-0545/#add-translation-to-the-language-switcher

> As soon as the translation hits:
>
> * 100% of bugs.html with proper links to the language repository issue tracker.
> * 100% of tutorial.
> * 100% of library/functions (builtins).
> 
> the translation can be added to the language switcher.

At least https://docs.python.org/pl/3/library/functions.html still has quite a bit of English in it.

**Comment by StanFromIreland** [comment]
@hugovk Its weird those bits cannot be translated for some reason. They don't show up in transifex and the progress % is 100%.
image

I will look in to it.

**Comment by StanFromIreland** [comment]
@hugovk I see, I translated those today, it will be updated around midnight If i remember correctly! Everything that is required is complete :)

**Comment by hugovk** [comment]
Great, let's check-in tomorrow :)

cc @m-aciek FYI

**Comment by AA-Turner** [comment]
@StanFromIreland in the `spam.ham` example, 'sausage' is translated in the code block but not in the inline code -- is this intentional?

https://docs.python.org/pl/3/library/functions.html#import__

-------

Z drugiej strony, instrukcja from spam.ham import eggs, sausage as saus skutkuje


```py
_temp = __import__('spam.ham', globals(), locals(), ['jajka', 'kielbasa'], 0)
jajka = _temp.jajka
kielbasa = _temp.kielbasa
```

A

**Comment by StanFromIreland** [comment]
@AA-Turner It has been fixed.

**Review by AA-Turner — APPROVED** [review]
I've spot-checked the tutorial, and confirmed that `bugs.html` and `library/functions.html` visually seem fully translated. The transifex project also reports 100% completion for the relevant `.po` files.

Congratulations @m-aciek, @StanFromIreland, and all of the other translators!

A

**Pull request merged**
