### PR TITLE
[WIP] Add french, japanese, and chinese

### PR DESCRIPTION
**Pull request by JulienPalard**
It's probably already in a nice state, but I'll still have to review this bit, I'm opening this pull request as a WIP to make it public.

There's still no crosslinks between translations, so this will still be invisible, but it's a nice step to test it slowly.

TODO:

- [ ] Check, add if missing, rsync in salt configuration, as this commit use it.

See: https://bugs.python.org/issue26546 and https://mail.python.org/pipermail/python-ideas/2016-March/038879.html

### CODE REVIEW

**Comment by berkerpeksag** [comment]
-1.

Some thoughts:

* The official Python documentation is actively maintained which means most of the translated content will eventually be outdated.
* We will get a lot of non-English bug reports because people will think that we do officially maintain non-English versions of the Python documentation. Even now we occasionally get one or two bug reports about outdated translations. I've spent a lot of my free time answering invalid bug reports on various open source projects (including Python, python.org, Gunicorn and PyPI) and I would like avoid unnecessary work load.

**Comment by JulienPalard** [comment]
> The official Python documentation is actively maintained which means most of the translated content will eventually be outdated.

We're actually aware of this, as its already happening while we're translating. And it's a good thing, obviously, that the upstream is maintained. But we're translating faster than the documentation is updated so for us all translators, just translating the updates will be holidays compared to translating everything. 

> We will get a lot of non-English bug reports

Good point, it look like we'll need to update bugs.python.org to clearly announce some rules to avoid this.

**Comment by berkerpeksag** [comment]
> When English sentence is updated, the English sentence is shown instead of
outdated translated sentence is not shown, until we translate it again.

Which will lead to another type of bug reports: "This sentence is not translated."

> Good point, it look like we'll need to update bugs.python.org to clearly announce some rules to avoid this.

Well, the problem is people won't read any of them. Also, bugs.p.o is not the only place to report documentation issues. They will use any Python related issue tracker like python.org and PyPI.

And no, using GitHub's issue template feature won't work. We do already use it in [PyPI](https://github.com/pypa/pypi-legacy/blob/master/.github/ISSUE_TEMPLATE.md) and [people don't read it](https://github.com/pypa/pypi-legacy/issues/567).

**Comment by methane** [comment]
@berkerpeksag Isn't it a general issue of OSS world?
Do you have better idea?

**Comment by berkerpeksag** [comment]
> Do you have better idea?

Yes, I do: Let translations live out of docs.p.o domain :)

Another problem with this idea is that we don't actually have any control over these repositories and their content (e.g. what should we do if someone accidentally puts an offensive content? It's much easier to miss things like this in a smaller volunteer-only community than in a larger English speaking community.)

**Comment by JulienPalard** [comment]
> Yes, I do: Let translations live out of docs.p.o domain :)

That's killing a fly with a bazooka. letting translations out of the official repository mean hiding them. Here in France I met a bunch of python developpers, but *no one* aware of the french translation.

So, basically you're saying "Let's keep non-english speakers far away from Python, I fear they report bugs".

> Another problem with this idea is that we don't actually have any control over these repositories and their content

That's why I opened the thread on Python-ideas, quote:

> # Where to host the translated files
> Currently we're hosting the *po* files in the afpy's (Francophone 
association for python) [6] github [1] but it may make sense to use (in 
the generation scripts) a more controlled / restricted clone in the 
python github, at least to have a better view of who can push on the 
documentation.
> We may want to choose between aggregating all translations under the 
same git repository but I don't feel it's useful.

So, I'm not against moving po files to github.com/python/whatever, it even make sense, and it's possible with this PR as repository, branches, and versions are only configuration.

**Comment by berkerpeksag** [comment]
> So, basically you're saying "Let's keep non-english speakers far away from Python, I fear they report bugs".

Please keep the conversation civil. I'm also a non-native English speaker and I didn't say any of that. I'm pretty sure that there are Python conferences and users groups in your area. I suggest using them to promote your work instead of trying to blame other volunteers.

**Comment by JulienPalard** [comment]
I'm not sure that keeping the translations out of d.p.o is a good way to avoid new issues: you said it yourself, b.p.o is already receiving issues about translations, even if they're almost known by nobody, so if we make them highly known (via conferences or via d.p.o), issues will flow anyway.

In the other hand translations are probably a good thing for Python accessibility, typically for young people, so I think it's worth the triaging time cost.

**Comment by JulienPalard** [comment]
As it is controversial, discussion continues in a more public place: https://mail.python.org/pipermail/python-ideas/2017-January/044490.html

**Comment by JulienPalard** [comment]
Closing this one, may reopen (probably another implementation) after further discussions following https://mail.python.org/pipermail/python-dev/2017-February/147416.html.

**Pull request closed without merging**
