### PR TITLE
Add common docs theme as a dependency

### PR DESCRIPTION
**Pull request by jonparrott**
Additionally update all existing dependencies in requirements.txt, as the common theme requires sphinx >= 1.6.0.

Context:
* https://github.com/python/cpython/pull/2017
* https://bugs.python.org/issue30607

### CODE REVIEW

**Comment by JulienPalard** [comment]
I ran a test build and everything went well, I'm merging this.

**Comment by JulienPalard** [comment]
Thanks, and thanks for upgrading dependencies in requirements.txt too.

**Comment by jonparrott** [comment]
Thank you!

**Comment by JulienPalard** [comment]
FYI server has built the new version: https://docs.python.org/3/

**Pull request merged**
