### PR TITLE
Update build_docs.py Adding italian language

### PR DESCRIPTION
**Pull request by GiuseppeAlaimo**
Adding italian language

### CODE REVIEW

**Comment by JulienPalard** [comment]
The italian translation [has not been maintained since 2019](https://github.com/python/python-docs-it), is it worth adding it?

**Comment by GiuseppeAlaimo** [comment]
Hi! I would like to start contributing in this project and the first thing I wanted to do is to enable italian language as I saw that there are already many pages that have been translated, but if that's not enough then I will start reviewing them first and make the required updates.

**Comment by m-aciek** [comment]
Already translated resources there, are:
* `bugs`,
* `about`,
* from tutorial:
  * `index`,
  * `appetite`,
  * `introduction`,
  * `interpreter`.

PS @GiuseppeAlaimo The next step for the repo probably should be updating the source strings, with use of `sphinx-intl` package as currently the repo holds the source strings for 3.9 version. Let me know if you'd use some help with this task.

**Comment by m-aciek** [comment]
Ah, instead of using `sphinx-intl` you can just update BRANCH variable in Makefile and run `make merge` having cpython cloned in the `../cpython/` directory, near to translations repository clone.

**Comment by JulienPalard** [comment]
@GiuseppeAlaimo Don't hesitate also to copy, or take inspiration, from the french `Makefile` (from python-docs-fr) uppon which the it repo has been built. it has envolved since. Do you have contacts with people having the right to merge on python-docs-it?

**Comment by GiuseppeAlaimo** [comment]
Thank you guys, I will look into that, and I will get in touch Alessandro Cucci about merging the PRs on python-docs-it

**Comment by m-aciek** [comment]
It has been built 🎉  🚀 🥳 

https://docs.python.org/it/3.11/

**Pull request merged**
